import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export const getServerSideProps = async() => {
  const text = await fetch('http://localhost:3000').then(res => res.text())

  return {
    props: {
      text
    }
  }
}

const Home: NextPage = (props: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <p>{props.text}</p>
      </body>
    </div>
  )
}

export default Home
